### ISSUE TITLE
lmdb problem 

### ISSUE THREAD

**Issue by PkuRainBow** [willyd/caffe-windows-dependencies#3]
Hi, I meet some problem when I want to build the lmdb database with your code.

Here is the link to the problem 
[issue](https://github.com/lmb-freiburg/flownet2/issues/97 ) 

Besides, there exist some dicussions about the problem with the built lmdb on windows here 
[dicussion](https://groups.google.com/forum/#!msg/caffe-users/GFaBKPeUvbw/Gf8mKra2BQAJ)

Can you help me?

**Comment by PkuRainBow** [comment]
@willyd

**Comment by willyd** [comment]
@PkuRainBow This project is was deprecated in favor of [caffe-builder](https://github.com/willyd/caffe-builder). LMDB in caffe-windows-dependencies is missing a patch that prevents one to create a DB larger than 2GB. caffe-builder has the fix. The [LMDB vcpkg port](https://github.com/Microsoft/vcpkg/tree/master/ports/lmdb) also has the fix.
